/**
 * Ledger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.9.0-beta.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Log } from '../models/Log';
import { HttpFile } from '../http/http';

export class ListLogs200ResponseCursorAllOf {
    'data': Array<Log>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<Log>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListLogs200ResponseCursorAllOf.attributeTypeMap;
    }

    public constructor() {
    }
}

