/**
 * Ledger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1.9.0-beta.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ListLogs200ResponseCursor } from '../models/ListLogs200ResponseCursor';
import { HttpFile } from '../http/http';

export class ListLogs200Response {
    'cursor': ListLogs200ResponseCursor;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cursor",
            "baseName": "cursor",
            "type": "ListLogs200ResponseCursor",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ListLogs200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

